apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  namespace: dapr-trafficcontrol
  labels:
    app: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      - name: simulation
        image: softstone1/simulation:1.0
        env:
          - name: MQTT_HOST
            value: mosquitto.dapr-trafficcontrol.svc.cluster.local
